version: "3.6"

services:

  api:
    build:
      context: ./app/api
      dockerfile: Dockerfile
    image: score-audio:api
    runtime: nvidia
    volumes:
      - ./storage:${STORAGE_DIR}
      - ./hub:${HUB_PATH}
    environment:
      - STORAGE_DIR=${STORAGE_DIR}
      - HUB_PATH=${HUB_PATH}
      - DEVICE_NUM=${DEVICE_NUM}
      - TZ=Asia/Seoul
    entrypoint:
      - uvicorn
    command:
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"

  web:
    build:
      context: ./app/web
      dockerfile: Dockerfile
    image: score-audio:web
    ports:
      - 8501:8501
    volumes:
      - ./storage:${STORAGE_DIR}
    environment:
      - API=http://api:8000/score
      - STORAGE_DIR=${STORAGE_DIR}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    entrypoint:
      - streamlit
    command:
      - "run"
      - "main.py"
    depends_on:
      - api

volumes:
  storage:
