version: "3.6"

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ellexidocker/about-classic:api
    runtime: nvidia
    volumes:
      - ./image:/image
      - ./audio:/audio
      - ./hub:/hub
    entrypoint:
      - uvicorn
    command:
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    environment:
      - CUDA_VISIBLE_DEVICES=3

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ellexidocker/about-classic:web
    ports:
      - "8501:8501"
    volumes:
      - ./image:/image
      - ./audio:/audio
    environment:
      - API=http://api:8000/compute
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    entrypoint:
      - streamlit
    command:
      - "run"
      - "main.py"
    depends_on:
      - api

volumes:
  image:
  audio:
