version: "3.6"

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ellexidocker/about-classic:api-base

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ellexidocker/about-classic:web-base
