version: "3.6"

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: score-audio:api-base

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: score-audio:web-base
